feat/rooms-links
datsmysong/app pull request #45
Opened 2024-01-15 11:11 UTC by GaspardBBY

2024-01-22 09:14 UTC, GaspardBBY reviewed
Somes bugs @ngomesodent

2024-01-22 09:14 UTC, GaspardBBY commented on expo/app/join/[roomCode].tsx
> +  let userProfileId: string = "";
Don't declare a variable here, you can add userProfileId on parameter of your function, and create state to use user in function addUserToRoom.

2024-01-22 09:14 UTC, GaspardBBY commented on expo/app/join/[roomCode].tsx
> +      await addUserToRoom();
If method return error, do not redirect to the active room page.

2024-01-22 09:14 UTC, GaspardBBY commented on expo/lib/types.ts
> +export interface StreamingPlatform {
You can delete this file.

2024-01-22 18:28 UTC, GaspardBBY commented on expo/app/join/[roomCode].tsx
> +        getParticipant(userProfileId).then((result) => {
the state will update after the render, so in getParticipant, use userProfile : 
`if (userProfile) {
        setUserProfileId(userProfile.user_profile_id);
        setIsConnected(true);
        getParticipant(userProfile.user_profile_id).then((result) => {`
this will prevent bugs

2024-01-23 07:39 UTC, ngomesodent commented on expo/app/join/[roomCode].tsx
> +        getParticipant(userProfileId).then((result) => {
Someone already did it for me, so it's not my job anymore :)

2024-01-23 13:35 UTC, MAXOUXAX requested changes
One chance!

2024-01-23 13:35 UTC, MAXOUXAX commented on expo/app/join/[roomCode].tsx
> +  const isInsideApplication = Device.deviceType === Device.DeviceType.PHONE;
```suggestion
    const isInsideApplication = Platform.OS !== "web";
```

2024-01-23 19:26 UTC, MAXOUXAX approved these changes
LGTM!

2024-01-24 16:09 UTC, GaspardBBY reviewed
LGTM

2024-01-24 16:25 UTC, MAXOUXAX approved these changes
LGTM!

2024-01-24 16:25 UTC, merged