Feat/get queue of room
datsmysong/app pull request #47
Opened 2024-01-15 16:12 UTC by drmolixcool

this feature was intended to access queue of room from id.
I added the adding and deleting track in given queue from link.
for the moment, only the Spotify track links were supported

2024-01-22 17:04 UTC, TheRealSharKzy commented on expo/app/(tabs)/rooms/index.tsx
> +      <View>
This view is useless since no style attached to it

2024-01-22 18:31 UTC, GaspardBBY commented on backend/src/musicplatform/TrackFactory.ts
> +// }).then(console.log)
clear this maybe

2024-01-22 18:40 UTC, GaspardBBY commented on expo/app/(tabs)/rooms/[id].tsx
> +};
Refactor on a component =>expo/components/room/TrackItem.tsx to exemple

2024-01-22 18:45 UTC, GaspardBBY commented on backend/src/server.ts
> +  // })
Cleen your code it's fine :d

2024-01-23 16:54 UTC, MAXOUXAX requested changes
Some changes to do, but overall it seems fine!

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/MusicPlatform.ts
> +  // private static singleton: any;
```suggestion
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/MusicPlatform.ts
> +    // let checkRegex = /^\/(?:[^(]|[^\\]\\\(|[^\\]\(\?)*\([^?](?:[^(]|[^\\]\\\(|[^\\]\(\?)*\)(?:[^(]|[^\\]\\\(|[^\\]\(\?)*\/.*$/
```suggestion
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/MusicPlatform.ts
> +    }
You should consider moving this regex validation step to another method, because this piece of code is a bit ugly and not readable at first
```ts
    const resultRegex = new RegExp(this.urlPattern.toString() + "|")
      .exec("")
      ?.slice(1).length;
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/MusicPlatform.ts
> +    MusicPlatform.musicPlatformsList.set(MusicPlatform.constructor.name, this);
This line looks ugly, you should consider another method, like a "register" pattern, where the Spotify implementation would do in its constructor
```ts
MusicPlatform.registerPlatform("Spotify", this);
```
for example

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/MusicPlatform.ts
> +    return new RegExp(this.urlPattern);
Why do you recreate a RegExp, is this to avoid side effects?
If not, consider returning the urlPattern property directly

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/MusicPlatform.ts
> +  getClass(): Function {
You are ignoring an eslint rule, but I don't see why you're typing that method instead of letting TypeScript decide for you

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/Spotify.ts
> +    const data = await spotify.tracks.get(id);
What happens if the track with the id `id` doesn't exist?

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/Spotify.ts
> +      artistName: data.artists[0].name,
Nope! We want to keep all artists of a song, not only the first one. artistName should be a formatted string with all artists.
For example, for the track "Martin Garrix & Bebe Rhexa - In The Name Of Love", the artistName should be "Martin Garrix, Bebe Rhexa"

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/Spotify.ts
> +      imgUrl: new URL(data.album.images[0].url).toString(),
Is the first image the higher resolution one? Why are you choosing this one in particular?

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/TrackFactory.ts
> +    // eslint-disable-next-line @typescript-eslint/ban-types
```suggestion
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/musicplatform/TrackMetadata.ts
> +    }
I'm not sure it's a good way of handling different types of inputs. The object you give to the method should be forced to at least have an id, or an url. This shouldn't be enforced at runtime.
Consider changing the type of the query argument to either be a `{ id: string }` or `{ url: string }`

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/room.ts
> +  private readonly tracks: Set<JSONTrack>;
```suggestion
  private readonly queue: Set<JSONTrack>;
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/room.ts
> +    this.uuid = randomUUID();
Why do you always assign a new random UUID to a new Room? The UUID is generated database-side, and when creating the room server-side you should create an object which has a matching uuid

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/room.ts
> +      return { currentActiveRoom: room.uuid, tracks: room.getTracks() };
```suggestion
      return { currentActiveRoom: room.uuid, queue: room.getQueue() };
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/room.ts
> +  }
```suggestion
  getQueueString(): string[] {
    return [...JSON.stringify(this.queue)];
  }

  getQueue(): JSONTrack[] {
    return [...this.queue];
  }
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/room.ts
> +    // let track = new URL(rawUrl).toString();
```suggestion
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/room.ts
> +    ) /*, new SoundCloud(), new AppleMusic()*/;
```suggestion
    );
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/route/RoomIdGET.ts
> +  console.log(RoomStorage.getRoomStorage());
```suggestion
```

2024-01-23 16:54 UTC, MAXOUXAX commented on backend/src/route/RoomIdGET.ts
This is a mocked room, you will need to implement the right room return in the future ;)

2024-01-23 16:54 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/[id].tsx
> +}
This should not be that way. You should probably check the existence of the environment variable inside the root layout, or something similar

2024-01-23 16:54 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/[id].tsx
> +  const [data, setData] = useState<RoomJSON>();
```suggestion
  const [queue, setQueue] = useState<RoomJSON>();
```

2024-01-23 16:54 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/_layout.tsx
> +      />
This will be moved inside the /rooms/:uuid page, not in a proper screen

2024-01-23 16:54 UTC, MAXOUXAX commented on expo/lib/socketio.ts
> +}
I don't know if this check should be here, it's probably not the right place

2024-01-23 16:54 UTC, MAXOUXAX commented on expo/lib/apiUrl.ts
> +  if (process.env.EXPO_PUBLIC_BACKEND_API) {
Please revert this change. The backend API URL should be determined dynamically if we're not on production

2024-01-24 12:51 UTC, drmolixcool commented on backend/src/musicplatform/MusicPlatform.ts
> +    MusicPlatform.musicPlatformsList.set(MusicPlatform.constructor.name, this);
it's old implementation, I have deleted this line and all referred those

2024-01-24 12:55 UTC, drmolixcool commented on backend/src/musicplatform/MusicPlatform.ts
> +    return new RegExp(this.urlPattern);
yes it's for side effects

2024-01-24 16:28 UTC, drmolixcool commented on backend/src/musicplatform/Spotify.ts
> +    const data = await spotify.tracks.get(id);
getJsonTrack is used only once times by Track.toJSON function, which skip all exceptions prevent block program cause API of music platform

2024-01-25 08:30 UTC, drmolixcool commented on backend/src/room.ts
> +    this.uuid = randomUUID();
it's temporary solution while other task is done

2024-01-25 08:35 UTC, drmolixcool commented on backend/src/room.ts
> +    ) /*, new SoundCloud(), new AppleMusic()*/;
I have let to help future dev on room

2024-01-25 08:59 UTC, drmolixcool commented on expo/lib/apiUrl.ts
> +  if (process.env.EXPO_PUBLIC_BACKEND_API) {
but I need this when I test with tunnel for expo go at IUT

2024-01-25 09:02 UTC, drmolixcool commented on backend/src/musicplatform/TrackMetadata.ts
> +    }
getJsonTrack may throw a error from Spotify subclass cause Spotify API, I have proof
And make this to catch all exception because external API are out of control

2024-01-28 21:27 UTC, MAXOUXAX commented
This deserves a big refactor and mostly a rewrite, but we don't have time for that right now, so we'll just ignore those problems.
Good luck @GaspardBBY and I in the future

2024-01-28 21:28 UTC, merged