Fix create room backend
datsmysong/app pull request #48
Opened 2024-01-16 08:19 UTC by TheRealSharKzy

Fixed room backend and now retrieving the user from the cookies of the request

2024-01-17 16:07 UTC, MAXOUXAX requested changes
Some changes, the most important one will be in @GaspardBBY's review

2024-01-17 16:11 UTC, GaspardBBY requested changes
Just a (maybe) problem for me 🥇

2024-01-17 16:11 UTC, GaspardBBY commented on backend/src/room.ts
> +    return { code: 401, message: "User not authenticated" };
I'm not sure it works, the code need to be send with the method `rep.code(...).send({your object)}`
Be careful if there is a bug, you do it many times fix in other case !

2024-01-18 10:45 UTC, MAXOUXAX approved these changes
LGTM

2024-01-18 11:15 UTC, GaspardBBY requested changes

2024-01-18 11:15 UTC, GaspardBBY commented on backend/src/room.ts
>          vote_skipping: voteSkipping,
You can insert only the object, without array to get the result return without data[0] :D

2024-01-18 11:15 UTC, GaspardBBY commented on backend/src/room.ts
- delete sur else, if error the code stop
- declare only here a constant "const configurationId" if you can (declare let null on the top of method is not pretty)

2024-01-18 11:15 UTC, GaspardBBY commented on backend/src/room.ts
>    }
You can improve this ! Return an object with the id, and on the front you can get it and navigate the user to the room (if not existe on your codebase because it's not your job just //TODO use roomid here)
I think to be perfect you can return "201" code, because you give some data to front.

2024-01-18 11:15 UTC, GaspardBBY commented on backend/src/route/StreamingServicesGET.ts
>        }
I would have done it like that:
`const { data: streamingServices, status, error } = await adminSupabase
    .from("streaming_services")
    .select("*");

  response.code(status).send(error ?? streamingServices);`

2024-01-18 16:37 UTC, GaspardBBY approved these changes
LGTM

2024-01-18 19:39 UTC, MAXOUXAX approved these changes

2024-01-18 19:39 UTC, merged