Feat/auth forms
datsmysong/app pull request #57
Opened 2024-01-17 22:14 UTC by GaspardBBY

Création de compte à partir d'une adresse email et d'un mot de passe.

2024-01-22 19:03 UTC, GaspardBBY commented on backend/src/route/AuthRegisterPOST.ts
> +};
Arbitrary values, to be reviewed

2024-01-23 10:15 UTC, MAXOUXAX requested changes
Some changes to do, but overall it seems pretty good!

2024-01-23 10:15 UTC, MAXOUXAX commented on expo/app/auth/register.tsx
> +    const data = await fetch(baseUrl + ":3000/auth/register", {
The port should be inside the baseUrl variable since it won't always be on port 3000, such as in production

2024-01-23 10:15 UTC, MAXOUXAX commented on expo/app/auth/register.tsx
> +    console.log("Result of register", data);
```suggestion
```

2024-01-23 10:15 UTC, MAXOUXAX commented on expo/app/auth/register.tsx
> +    // alignItems: "center",
```suggestion
```

2024-01-23 10:15 UTC, MAXOUXAX commented on expo/components/ControledInput.tsx
> +          {errorMessage ?? "Le champs est invalide"}
```suggestion
          {errorMessage ?? "Le champ est invalide"}
```

2024-01-23 10:15 UTC, MAXOUXAX commented on expo/components/ControledInput.tsx
> +export default function ControledInput({
```suggestion
export default function ControlledInput({
```

2024-01-23 10:16 UTC, ngomesodent commented on expo/components/CustomTextInput.tsx
> +  onSubmit?: () => void;
Change name to fit other branches

2024-01-23 18:54 UTC, TheRealSharKzy reviewed
2 minors suggestions

2024-01-23 18:54 UTC, TheRealSharKzy commented on backend/src/authRoutes.ts
> +          required: ["email", "password"],
Don't you need to put "username" in required, since you retrieve it every time in AuthRegister and I didn't see any default value

2024-01-23 18:54 UTC, TheRealSharKzy commented on expo/app/auth/register.tsx
> +              message: "Le nom d'utilisateur est trop court",
Maybe tell the user that the username needs to have more than 5 characters

2024-01-23 23:09 UTC, drmolixcool requested changes
- on home page, label of button link this feature have name "Rejoindre avec un adresse mail" but when I click on, you are redirected to login page and not register page.
- when I register me, I receive a confirmation mail but the link "Confirm your mail" but the mail is very bad designed then when I click, the callback goes to anything : 
what the final link after redirection http://localhost:3000/#access_token=eyJhbGciOiJIUzI1NiIsImtpZCI6IkFwR3VneFNLTi93REhTYjAiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzA2MDU0OTEwLCJpYXQiOjE3MDYwNTEzMTAsImlzcyI6Imh0dHBzOi8vY2thbHNkY3dyb2Z4dmd4c2x3aXYuc3VwYWJhc2UuY28vYXV0aC92MSIsInN1YiI6IjgwOTQzZDE3LTc0MmEtNGU3YS04MjFjLTdlOTU0ZTE2NDMxZCIsImVtYWlsIjoieGVpdG91Y29iaWJvaS02NjUzQHlvcG1haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6e30sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoib3RwIiwidGltZXN0YW1wIjoxNzA2MDUxMzEwfV0sInNlc3Npb25faWQiOiI3NzExYmI5NS1mN2UyLTRiMmYtODQwZC1jYzBmOWQzNGMwNDcifQ._I-dEDcnkVKD4MxtCJ_S6-YxWY8Xph6xgbrVrEhfgwk&expires_at=1706054910&expires_in=3600&refresh_token=CDBdWEAE7SF39Yg1vPzIqw&token_type=bearer&type=signup
![image](https://github.com/datsmysong/app/assets/51742551/7a2e0556-7841-40d2-a18b-612208af0d94)

2024-01-24 16:30 UTC, MAXOUXAX requested changes
just some tiny changes! @GaspardBBY

2024-01-24 16:30 UTC, MAXOUXAX commented on backend/.env.local.example
> +FRONT_END_URL=localhost:8081
```suggestion
FRONTEND_URL=localhost:8081
```

2024-01-24 16:30 UTC, MAXOUXAX commented on backend/src/route/AuthRegisterPOST.ts
> +  const urlFront = process.env.FRONT_END_URL;
```suggestion
  const urlFront = process.env.FRONTEND_URL;
```

2024-01-24 16:30 UTC, MAXOUXAX commented on backend/src/server.ts
> +if (!process.env.FRONT_END_URL) {
```suggestion
if (!process.env.FRONTEND_URL) {
```

2024-01-24 21:11 UTC, merged