Joining a room with a code
datsmysong/app pull request #65
Opened 2024-01-22 16:06 UTC by ngomesodent

2024-01-23 20:20 UTC, MAXOUXAX requested changes
Just some tiny adjustements!

2024-01-23 20:20 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/index.tsx
> +  // TODO: If the user is already in a room, the button "Rejoindre une salle" should redirect him to the room he is in.
While interesting, that hasn't been discussed before I think. Right now, nothing prevents a user from being in multiple active rooms at the same time.

2024-01-23 20:20 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/join.tsx
> +      Keyboard.dismiss();
The keyboard should be dismissed when the user submits the form. Period.
It shouldn't be dismissed only when an error occurs

2024-01-24 15:47 UTC, GaspardBBY approved these changes
LGTM

2024-01-24 16:11 UTC, TheRealSharKzy reviewed
LGTM

2024-01-24 16:14 UTC, TheRealSharKzy approved these changes
LGTM

2024-01-24 16:15 UTC, MAXOUXAX approved these changes
Just a single comment to remove (because it's undiscussed) but otherwise it LGTM!

2024-01-29 16:13 UTC, TheRealSharKzy approved these changes
LGTM

2024-01-30 13:34 UTC, MAXOUXAX approved these changes
LGTM!!!

2024-01-30 13:34 UTC, GaspardBBY approved these changes
LGTM

2024-01-30 13:38 UTC, merged