feat/room-history-view
datsmysong/app pull request #66
Opened 2024-01-22 16:08 UTC by MAXOUXAX

2024-01-22 19:01 UTC, GaspardBBY reviewed
Everything is beautiful, keep it up

2024-01-23 16:42 UTC, TheRealSharKzy reviewed
Not sure if my reviews are really relevant, but overall it seems good

2024-01-23 16:42 UTC, TheRealSharKzy commented on backend/src/route/RoomGET.ts
> +    if (participant.profile.user_profile) {
If the participant has no user_profile don't you need to also add him, for example if he is anonymous, he won't have a user_profile but he still is a participant of the room. Maybe you're doing that because anonymous participant are not implemented in the app for now...

2024-01-23 16:42 UTC, TheRealSharKzy commented on backend/src/route/RoomGET.ts
> +    if (participant.profile.user_profile) {
Or is it the return below the if ?

2024-01-23 16:42 UTC, TheRealSharKzy commented on expo/components/RoomHistory.tsx
> +      if (!user) return;
Maybe tell something to the user like "no user connected"

2024-01-24 08:40 UTC, MAXOUXAX commented on backend/src/route/RoomGET.ts
> +    if (participant.profile.user_profile) {
The anonymous participant case is handled just below that if yes. If it's a user, then we add the full profile including the user profile, and since it's inside a return, all code below won't be executed, making the return below the default for when the user is an anonymous one

2024-01-24 08:55 UTC, MAXOUXAX commented on expo/components/RoomHistory.tsx
> +      if (!user) return;
If the user isn't authenticated, the "middleware" inside the root layout will redirect the user to the onboarding page. We don't really have to handle users not logged in inside our app in our pages, since most of them aren't accessible to anonymous users - except the future view for active rooms

2024-01-29 16:39 UTC, TheRealSharKzy requested changes
Overall seems good, 2 minor changes I think

2024-01-29 16:39 UTC, TheRealSharKzy commented on expo/components/RoomHistory.tsx
> +            <InfoCard
Isn't it good to use a flatList for all the infoCard ?

2024-01-30 07:56 UTC, MAXOUXAX commented on expo/components/RoomHistory.tsx
> +              return <InactiveMusic key={song.name} music={song} />;
It is useful and even mandatory!
https://react.dev/learn/rendering-lists

2024-01-30 08:36 UTC, MAXOUXAX commented on expo/components/RoomHistory.tsx
> +            <InfoCard
This doesn't seem useful for now since there won't be more than 3 elements, and this isn't a proper "list of items".

2024-02-14 10:40 UTC, MAXOUXAX reviewed
A few changes but on a good path

2024-02-14 10:40 UTC, MAXOUXAX commented on backend/src/route/InactiveRoomUserIdGET.ts
> +export default async function InactiveRoomUserIdGET(
The name of this file is really unclear, I guessed from the usage that it returns a list of all rooms that the user was part of

2024-02-14 10:40 UTC, MAXOUXAX commented on backend/src/route/RoomGET.ts
> +};
Since this code is now running on the server, we probably don't need this method right?

2024-02-14 10:40 UTC, MAXOUXAX commented on backend/src/server.ts
>  server.get("/room/:id", RoomIdGET);
There needs to be some work done about that, since we currently have a /room/:id route, and a /rooms/:id route. I'm not sure what's the difference between the two but I'm pretty sure both shouldn't co-exist

2024-02-14 10:40 UTC, MAXOUXAX commented on commons/room-types.ts
Maybe those types can be changed / refactored by using some types from another type file in the same directory

2024-02-14 10:40 UTC, MAXOUXAX commented on expo/components/RoomHistoryInfoCard.tsx
> +      </Link>
The whole room info card should be the link.
Also the link is wrong, it should just send to /rooms/${room.id}

2024-02-14 10:40 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/[id]/history.tsx
This page shouldn't exist

2024-03-21 13:20 UTC, MAXOUXAX commented
@TheRealSharKzy is this ready for review?

2024-03-22 15:22 UTC, GaspardBBY requested changes
Some changes with hook utilization, if you need help, ask me ! Moreover, you can satisfy ESLint comments.

2024-03-22 15:22 UTC, GaspardBBY commented on expo/components/RoomHistory.tsx
> +  }, []);
You never use User, if it was just to verify if he's connected, middleware make it before this render👍

2024-03-23 14:44 UTC, TheRealSharKzy commented on expo/components/RoomHistory.tsx
> +  }, []);
I don't really know since It's @MAXOUXAX who has written this file, but I'll delete it anyway

2024-03-26 09:51 UTC, GaspardBBY approved these changes
LGTM

2024-04-03 14:18 UTC, merged