feat/room qr code
datsmysong/app pull request #69
Opened 2024-01-24 14:52 UTC by ngomesodent

2024-01-24 16:08 UTC, MAXOUXAX requested changes
Looking good for now!

2024-01-24 16:08 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/[id]/index.tsx
> +export default function TabsRooms() {
This shouldn't be called TabsRoom but rather "RoomView" or something like that

2024-01-24 17:00 UTC, drmolixcool approved these changes

2024-01-24 19:04 UTC, ngomesodent commented on expo/app/(tabs)/rooms/[id]/index.tsx
> +export default function TabsRooms() {
My bad forgot to rename it. Done :)

2024-01-31 13:37 UTC, MAXOUXAX approved these changes
Just one component name to change, but otherwise LGTM!

2024-01-31 13:37 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/[id]/qrcode.tsx
> +export default function InvitationModal() {
```suggestion
export default function QRCodeModal() {
```

2024-01-31 14:22 UTC, merged