feat/manage-account
datsmysong/app pull request #70
Opened 2024-01-24 15:20 UTC by GaspardBBY

Page informations personnelles

2024-01-24 16:32 UTC, TheRealSharKzy requested changes
Overall LGTM just one little thing

2024-01-24 16:32 UTC, TheRealSharKzy commented on expo/app/account/personal-info.tsx
> +        <View>
Isn't that view useless for now since it has no styles and no props

2024-01-24 16:49 UTC, MAXOUXAX requested changes
you're on a great path!

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/app/(tabs)/Profile.tsx
> +      </Link>
You can replace this Link with a Button component, since the replace prop isn't a wanted effect

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/app/account/_layout.tsx
> +        name="personal-info"
```suggestion
        name="edit"
```

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/app/account/index.tsx
> +      </Link>
Wrapping the SettingsOptions component with a Link looks verbose since every SettingsOptions component will be a link to a specific page.
Consider moving the link inside the component itself and pass the href as a prop, or use a Pressable replacing the current route with `router.replace`

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/app/account/personal-info.tsx
> +          Sauvegarer
:)

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/components/profile/Avatar.tsx
> +const Avatar = forwardRef((props: Props, ref) => {
```suggestion
interface AvatarProps {
  onImageLoad: () => void;
}

const Avatar = forwardRef((props: AvatarProps, ref) => {
```

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/components/profile/Avatar.tsx
> +      .getPublicUrl(path + "?caches=" + Math.random());
```suggestion
      .getPublicUrl(path + "?avoidCache=" + Math.random());
```

2024-01-24 16:49 UTC, MAXOUXAX commented on expo/components/profile/Avatar.tsx
> +    await supabase.storage.from("avatars").remove([fileName]);
```suggestion
```

2024-01-29 16:56 UTC, ngomesodent reviewed
Seems good 👍

2024-01-29 16:56 UTC, ngomesodent commented on expo/app/account/edit.tsx
> +            label="Nom d'uilisateur"
Little typo right here

2024-01-29 16:56 UTC, ngomesodent commented on expo/app/account/edit.tsx
> +  const [subbmitable, setSubbmitable] = useState<boolean>(false);
submittable*

2024-01-29 16:56 UTC, ngomesodent commented on expo/app/account/edit.tsx
> +    const usernameWithoutAt = username.replace("@", "");
Why asking the user to put a "@" if you remove it after ? Maybe it's to distinguish the username from other inputs but it's useless imo :)

2024-01-29 16:56 UTC, ngomesodent commented on expo/app/account/edit.tsx
> +    const succedResum: string[] = [];
succeed* and i don't know what's the other word

2024-01-29 16:56 UTC, ngomesodent commented on expo/lib/inputRestriction.ts
> +    value: 4,
Okay but Yu will not be able to choose his name as a username...

2024-01-29 16:59 UTC, GaspardBBY commented on expo/lib/inputRestriction.ts
> +    value: 4,
Don't understand can you explain me

2024-01-30 20:58 UTC, GaspardBBY commented on expo/app/account/edit.tsx
> +      // si l'utilisateur a un provider autre que email, on ne peut pas changer l'email
removed

2024-02-01 07:56 UTC, MAXOUXAX approved these changes
LGTM

2024-02-01 08:21 UTC, merged