Feat/room parameters menu
datsmysong/app pull request #80
Opened 2024-01-29 16:05 UTC by TheRealSharKzy

2024-01-29 16:23 UTC, drmolixcool commented on backend/src/route/RoomConfigurationUpdatePOST.ts
> +  const voteSkipping = bodyParams.voteSkipping;
```suggestion
  const voteSkipping = bodyParams.voteSkipping;
```

2024-01-29 17:09 UTC, drmolixcool requested changes
like eslint analyse, you might remove braces : "{"and "}" surround string into JSX Element properties
Else it's only recommend to improve your code in my opinion
Good luck 🍀

2024-01-29 17:09 UTC, drmolixcool commented on expo/app/(tabs)/rooms/[id]/settings.tsx
> +    alignItems: "flex-start",
It's default in react native : https://reactnative.dev/docs/flexbox
```suggestion
```

2024-01-29 17:09 UTC, drmolixcool commented on expo/components/NewParametersList.tsx
> +    display: "flex",
```suggestion
```

2024-01-29 17:09 UTC, drmolixcool commented on expo/components/NewParametersList.tsx
> +    alignItems: "flex-start",
```suggestion
```

2024-01-29 17:09 UTC, drmolixcool commented on expo/components/NewParametersList.tsx
> +    display: "flex",
```suggestion
```

2024-01-29 17:09 UTC, drmolixcool commented on expo/components/NewParametersList.tsx
> +    flexDirection: "column",
```suggestion*
```

2024-01-29 17:09 UTC, drmolixcool commented on expo/components/NewParametersList.tsx
> +    alignItems: "flex-start",
```suggestion*
```

2024-01-31 16:49 UTC, MAXOUXAX requested changes
There are some changes, especially on the backend side (switching to dynamic routes like the rest of the project).
Also, the settings UI should probably use react-hook-form later down the road (since it's a form, and needs input validation, etc, just like auth forms), but since it's quite a big refactor and we're in a rush, we can probably update that later down the road.
Also, don't forget to fix eslint warnings!

2024-01-31 16:49 UTC, MAXOUXAX commented on expo/components/RoomConfigurationParametersList.tsx
> +  const [maxMusicPerUser, setMaxMusicPerUser] = React.useState("5");
Why didn't you just import useRef and useState from React just like in other components?

2024-01-31 16:49 UTC, MAXOUXAX commented on backend/src/route/RoomGET.ts
I'm not really sure how that got into main, but using a query parameter to get the room id seems a bit weird for a RESTful API. Consider turning that into a dynamic route (`/rooms/another_uuid/`)

2024-01-31 16:49 UTC, MAXOUXAX commented on backend/src/route/RoomConfigurationGET.ts
Same remark as with `RoomGET.ts`, why get the configuration id from query params instead of just using a dynamic route?

2024-01-31 16:49 UTC, MAXOUXAX commented on backend/src/route/RoomConfigurationUpdatePOST.ts
Same remark as with other routes, just use a dynamic route

2024-02-13 15:06 UTC, GaspardBBY commented on expo/components/RoomConfigurationParametersList.tsx
> +      </View>
You can add submit button, your submit it’s not necessarily intuitive for everyone.

2024-02-14 10:09 UTC, MAXOUXAX requested changes

2024-02-14 10:09 UTC, MAXOUXAX commented on expo/components/RoomConfigurationParametersList.tsx
This component seems a bit big, maybe we could cut it down in some way

2024-03-04 16:44 UTC, merged