refactor: add non-tested code for archive an active room
datsmysong/app pull request #81
Opened 2024-01-29 16:33 UTC by drmolixcool

2024-01-29 16:55 UTC, GaspardBBY reviewed
Don't forget to make rebase everyday, continue like that

2024-01-29 16:55 UTC, GaspardBBY commented on backend/src/server.ts
> +
Can you add websocket types  in `declare module "fastify" {
  interface FastifyInstance {
    io: Server<{
      hello: (a: string) => void;
    }>;
  }
}
`
it's supposed to fix run backend with node :D

2024-01-29 16:55 UTC, GaspardBBY commented on expo/app/(tabs)/rooms/[id]/index.tsx
> +    const response = await fetch(url + "/end");
watch out to not forget {credentials:true}

2024-01-29 16:55 UTC, GaspardBBY commented on backend/src/route/RoomEndGET.ts
> +    .eq("account_id", data.user.id)
It should not work, you can access to host_user_profile_id here not account_id

2024-01-29 16:55 UTC, GaspardBBY commented on backend/src/route/RoomEndGET.ts
> +  reply.send("this room is archived");
code 200, message is useless

2024-01-30 18:41 UTC, GaspardBBY requested changes
Only some refactor

2024-01-30 18:41 UTC, GaspardBBY commented on backend/src/route/RoomEndGET.ts
> +  if (!data.user) return reply.code(404).send("user is impossible to find");
use unauthorizedResponse() function in src/room.ts (you can export this method or refactor)

2024-01-30 18:41 UTC, GaspardBBY commented on backend/src/route/RoomEndGET.ts
> +  return reply;
return reply.code(200) to help the frontend developer

2024-01-31 16:16 UTC, TheRealSharKzy requested changes
Just one thing (I think), but the rest is OK for me

2024-01-31 16:28 UTC, ngomesodent requested changes

2024-01-31 16:28 UTC, ngomesodent commented on backend/src/route/RoomEndGET.ts
> +    .single();
I don't think you need to do a joint. All the informations you need are in the room_users table.

2024-01-31 16:28 UTC, ngomesodent commented on expo/app/(tabs)/rooms/[id]/index.tsx
> +    //     .then((data: ActiveRoomSkeleton) => setData(data))
Delete it then. Or if you need it for later just save it in a text file.

2024-01-31 16:28 UTC, ngomesodent commented on expo/app/(tabs)/rooms/[id]/index.tsx
> +            </Button>
I don't know if it should be here. In my memory it was under the list of tracks

2024-02-01 07:52 UTC, drmolixcool commented on backend/src/route/RoomEndGET.ts
> +    .single();
it's for get the host not participants, rooms have foreign key "host_user_id"

2024-02-01 08:08 UTC, MAXOUXAX requested changes
Just a few refactoring changes

2024-02-01 08:08 UTC, MAXOUXAX commented on backend/src/room.ts
>  }
Maybe this method should be moved inside a utils class since it can be reused basically on any route

2024-02-01 08:08 UTC, MAXOUXAX commented on backend/src/route/RoomEndGET.ts
> +    .single();
You need to check if the room is active when querying that

2024-02-01 08:49 UTC, merged