feat/remove track
datsmysong/app pull request #83
Opened 2024-01-30 13:19 UTC by ngomesodent

When the user presses the "3 dots" icon, a context menu is showed with a "delete" option, that when clicked, removes the track from the track list.

2024-01-31 16:32 UTC, TheRealSharKzy approved these changes
LGTM

2024-02-01 08:02 UTC, MAXOUXAX requested changes
Looking good overall, just some tiny changes! :)

2024-02-01 08:02 UTC, MAXOUXAX commented on expo/app/(tabs)/rooms/[id]/index.tsx
> +        <MenuProvider>
This provider should be moved inside the root layout of our application, so we are able to use a popup menu everywhere without having to reinstantiate a MenuProvider

2024-02-01 08:02 UTC, MAXOUXAX commented on expo/lib/room-utils.ts
> +}
This method is called `getHost` but it doesn't seem to return a host, since it takes a room id, a userProfile id, and in fact returns a room if the given userProfile id is the host of the given room id. I guess it could be called `getRoomFromHost` or something along those lines

2024-02-01 10:06 UTC, merged